- block:

  - name: set OS family dependent variable
    include_vars: '{{ ansible_os_family }}.yml'
    tags: always

  - name: OS dependent variables
    include_vars: '{{ item }}'
    with_first_found:
      - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
        skip: true
    tags: always
  - name: Add group "krisha1" to remote server
    become: yes
#    remote_user: root
    group:
      name: krisha1
      gid: 2010 
      state: present
  - name: Add user "krisha1" to the remote server
    become: yes
#    remote_user: root
    user:
      name: krisha1
      password: $1$SomeSalt$FQ8j8BGQWfkLvglE85Qiu0
      comment: "Privileged User"
      uid: 2010
      group: krisha1
      append: yes
      shell: /bin/bash
      generate_ssh_key: yes
      ssh_key_bits: 2010
      ssh_key_file: .ssh/id_rsa

  - name: Add krisha1 user to the sudoers
    become: yes
#    remote_user: root
    copy:
      dest: "/etc/sudoers.d/krisha1"
      content: "krisha1  ALL=(ALL)  NOPASSWD: ALL"
 
  - name: Deploy SSH Key
    become: yes
#    remote_user: root
    authorized_key: 
      user: krisha1
      key: "{{ lookup('file', '/home/bselinadmin/.ssh/id_rsa.pub') }}"
      state: present

  - name: Install Auditd package
    become: yes
    package:
      name: '{{ auditd.auditd_package }}'
      state: present


  - name: configure Auditd
    become: yes
    template:
      src: 'etc/audit/auditd.conf.j2'
      dest: '/etc/audit/auditd.conf'
      owner: root
      group: root
      mode: 0640
      backup: yes
    notify:
      - restart auditd

  - name: Configure user limits
    become: yes
    template: 
      src: etc/security/limits.conf.j2
      dest: /etc/security/limits.conf
      owner: root
      group: root
      mode: 0660
      backup: yes

  - name: Set Login definations
    become: yes
    template: 
      src: etc/login.defs.j2
      dest: /etc/login.defs
      owner: root
      group: root
      mode: 0644
      backup: yes
    when: 
      - (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")

  - name: get openssh-version
    shell: ssh -V 2>&1 | sed -r 's/.*_([0-9]*\.[0-9]).*/\1/g'
    args:
      executable: /bin/sh
    changed_when: false
    register: openssh_version
    check_mode: no

  - include_tasks: crypto.yml

  - include_tasks: sshd.yml
    when: sshd_hardening

  - include_tasks: ssh.yml
    when: ssh_hardening

#  - include_tasks: public-keys.yml
#    when:
#      - openssh_keys
#      - public_keys != ""
