---
# handlers file for linux-hardening
- name: restart auditd
  service:
    name: auditd
    state: started
- name: "(Handler: All Linux OSs) Restart sshd"
  become: yes
  service:
    name: "{{ sshd_service }}"
    state: restarted
