---
- hosts: rhel7
  gather_facts: false
  become: yes
  vars:
    Peripheral: "192.168.252.44, 192.168.252.45"
    PROD: "192.168.152.22, 192.168.152.26"
  vars_prompt:
    prompt: "Enter the ldap_env (PROD|Peripheral)"
    name: ldap_env
    default: Peripheral
    private: no

  tasks:
    - name: Install a list of packages of openldap
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - nss-pam-ldapd.x86_64
        - nss-pam-ldapd
        - openldap
        - openldap-clients
        - nfs-utils
      
    - name: Configure ldap client on Peripheral
#      debug:
#        msg: "Testing ...Peripheral {{ ldap_env }}"
      shell: | 
        "authconfig --enableforcelegacy --update"
        "authconfig --enableldap --enableldapauth --ldapserver={{ ldap_env }} --ldapbasedn=dc=bseindia,dc=com --enableforcelegacy --update"
      when: 
        - ldap_env == 'Peripheral'

    - name: Configure ldap client on PROD
#      debug:
#        msg: "Testing ....PROD {{ ldap_env }}"
      shell: |
        "authconfig --enableforcelegacy --update"
        "authconfig --enableldap --enableldapauth --ldapserver={{ ldap_env }} --ldapbasedn=dc=bseindia,dc=com --enableforcelegacy --update"
      when:
        - ldap_env == 'PROD'
   
 
